In [2]:
import torch
torch.__version__

'2.7.1+cu126'

In [3]:
# scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([3, 5, 7])
vector

tensor([3, 5, 7])

In [ ]:
# Check the number of dimensions of vector
vector.ndim

1

In [ ]:
# Check shape of vector
vector.shape

torch.Size([3])

In [ ]:
# Matrix
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [19]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [ ]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR2 = torch.tensor([[
                        [1,2,3],
                        [4,5,6],
                        [7,8,9]
                        ],
                       [
                        [1,2,3],
                        [4,5,6],
                        [7,8,9],
                        
                       ]])

TENSOR.ndim

3

In [22]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [36]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand((3,4))
random_tensor.ndim, random_tensor.shape, random_tensor.dtype, random_tensor

(2,
 torch.Size([3, 4]),
 torch.float32,
 tensor([[0.1923, 0.6853, 0.3101, 0.0236],
         [0.5619, 0.6767, 0.8990, 0.3952],
         [0.2885, 0.4019, 0.0240, 0.9101]]))

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_tensor = torch.rand((3,224,224))
random_tensor

tensor([[[0.1223, 0.2745, 0.5122, 0.7969],
         [0.7546, 0.3671, 0.8437, 0.1475],
         [0.0357, 0.5523, 0.3721, 0.3473],
         [0.0917, 0.4314, 0.3853, 0.0781]],

        [[0.4531, 0.4944, 0.8272, 0.5291],
         [0.9487, 0.6086, 0.8472, 0.4660],
         [0.8712, 0.8913, 0.8411, 0.7059],
         [0.2251, 0.7380, 0.6135, 0.2664]],

        [[0.4182, 0.1320, 0.9618, 0.0558],
         [0.9894, 0.4035, 0.9919, 0.6374],
         [0.4224, 0.0719, 0.8167, 0.2700],
         [0.6161, 0.9197, 0.1207, 0.6360]]])

In [42]:
# Create a tensor of all zeros
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
# Create a tensor of all ones
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [45]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros, ten_zeros.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]))

In [50]:
# Default datatype for tensors is float32
float_32_tensor = torch.rand((3), 
                             dtype=torch.float16, 
                             requires_grad=None, 
                             device = None)
float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([0.5908, 0.5884, 0.4565], dtype=torch.float16),
 torch.Size([3]),
 torch.float16,
 device(type='cpu'))

In [51]:
# Create a tensor
some_tensor = torch.rand((3,4))

# Find out details about it
print(some_tensor)
print(f"Shape of tensor : {some_tensor.shape}")
print(f"device of tensor : {some_tensor.device}")
print(f"dtype of tensor : {some_tensor.dtype}")

tensor([[0.8555, 0.8164, 0.8743, 0.4628],
        [0.9641, 0.9650, 0.7207, 0.0602],
        [0.2397, 0.7271, 0.8275, 0.3272]])
Shape of tensor : torch.Size([3, 4])
device of tensor : cpu
dtype of tensor : torch.float32


In [52]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor, tensor.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [53]:
tensor+10

tensor([11, 12, 13])

In [54]:
tensor*10

tensor([10, 20, 30])

In [55]:
10- tensor 

tensor([9, 8, 7])

In [56]:
tensor = tensor-10
tensor

tensor([-9, -8, -7])

In [57]:
tensor = tensor +10

In [58]:
tensor

tensor([1, 2, 3])

In [61]:
print(tensor ,"*", tensor)
print(f"equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [62]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [71]:
%%time
tensor.matmul(tensor) 

CPU times: user 1.37 ms, sys: 440 μs, total: 1.81 ms
Wall time: 1.26 ms


tensor(14)

In [72]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
f=0
for i in tensor:
    f=f+  i*i
print(f)  

tensor(14)
CPU times: user 3.82 ms, sys: 3.79 ms, total: 7.6 ms
Wall time: 3.91 ms


In [73]:
torch.matmul(tensor, tensor)

tensor(14)

In [83]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])
tensor_B = torch.tensor([[4,5],
                         [7,8],
                         [9,7]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[14, 23, 23],
        [23, 38, 39],
        [32, 53, 55]])

In [79]:
tensor_A, tensor_B

(tensor([[1, 2],
         [2, 3],
         [3, 4]]),
 tensor([[4, 5],
         [7, 8],
         [9, 7]]))

In [77]:
tensor_B.T

tensor([[4, 7, 9],
        [5, 8, 7]])

In [80]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[14, 23, 23],
        [23, 38, 39],
        [32, 53, 55]])

Output shape: torch.Size([3, 3])


In [88]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

linear = torch.nn.Linear(in_features= 2,
                         out_features=6)
x=torch.randn((3,2))
output=linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 0.9888,  0.3117,  0.3418, -0.0555,  0.5656,  0.4033],
        [ 0.5818,  1.2026,  0.7456,  0.9326, -1.0080, -0.5535],
        [ 0.4686, -0.4747,  0.1364, -0.6240,  1.3291,  0.4219]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [89]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
from numpy import float32


print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [91]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [93]:
# Create a tensor and check its datatype
tensor = torch.arange(10.,100., 10)
tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [99]:
tensor_float16= tensor.type(torch.float16)


tensor_int8= tensor.type(torch.int8)
tensor_int8, tensor_float16

(tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8),
 tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16))

In [101]:
x= torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [106]:
x_reshaped = x.reshape((1,7))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [107]:
z = x.view((1,7))
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [110]:
z[:,0] =5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [122]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x,x], dim=0)
x_stacked.shape,x_stacked, x

(torch.Size([5, 7]),
 tensor([[5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.]]),
 tensor([5., 2., 3., 4., 5., 6., 7.]))

In [124]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [128]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
New shape: torch.Size([7, 1])


In [129]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [130]:

x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [138]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [134]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")


First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [136]:
# Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:,0])

tensor([[1, 2, 3]])


In [139]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:,:,1])

tensor([[2, 5, 8]])


In [140]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:,1,1])

tensor([5])


In [141]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# NumPy array to tensor

import numpy as np

array = np.arange(1,8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [147]:
array = array + 1
array

array([3, 4, 5, 6, 7, 8, 9])

In [150]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [152]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand((3,4))

torch.random.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand((3,4))

random_tensor_c == random_tensor_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [153]:
!nvidia-smi

Sat Jul  5 18:39:07 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.09              Driver Version: 571.96         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8              7W /   30W |     172MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [154]:
torch.cuda.is_available()

True

In [155]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [156]:
device

'cuda'

In [157]:
torch.cuda.device_count()

1

In [158]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [159]:
tensor = tensor.to(device)
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))